;              
CREATE USER IF NOT EXISTS "SA" SALT 'e9fd9d3dfc06b666' HASH '5b8c8442dbacb929ea86f1bb4f3f5bc03fb79183052df9b26539408ed0f3caea' ADMIN;          
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;    
CREATE MEMORY TABLE "PUBLIC"."PHONE"(
    "ID" BIGINT NOT NULL,
    "CITYCODE" VARCHAR(255),
    "COUNTRYCODE" VARCHAR(255),
    "NUMBER" VARCHAR(255)
);      
ALTER TABLE "PUBLIC"."PHONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PHONE;    
CREATE MEMORY TABLE "PUBLIC"."USER"(
    "ID" BINARY NOT NULL,
    "CREATED" TIMESTAMP,
    "EMAIL" VARCHAR(255),
    "ISACTIVE" BOOLEAN,
    "LAST_LOGIN" TIMESTAMP,
    "MODIFIED" TIMESTAMP,
    "NAME" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "TOKEN" VARCHAR(255)
);              
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;     
CREATE MEMORY TABLE "PUBLIC"."USER_PHONES"(
    "USER_ID" BINARY NOT NULL,
    "PHONES_ID" BIGINT NOT NULL
);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_PHONES;              
ALTER TABLE "PUBLIC"."USER_PHONES" ADD CONSTRAINT "PUBLIC"."UK_LPX6WAWT7F9HQOLFY260IAVA4" UNIQUE("PHONES_ID"); 
ALTER TABLE "PUBLIC"."USER_PHONES" ADD CONSTRAINT "PUBLIC"."FK8A99K1BVO4HGVIB6T1UI8RIOB" FOREIGN KEY("PHONES_ID") REFERENCES "PUBLIC"."PHONE"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."USER_PHONES" ADD CONSTRAINT "PUBLIC"."FKDFSLJ94KBJQVP71KJJC36IIJE" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;      
